### ISSUE TITLE
Impossible d'associer les outils externes sous mac (exiftool)

### ISSUE THREAD

**Issue by lionpeloux** [micmacIGN/InterfaceCEREMA#1]
Bonjour,

J'ai installé micmac et l'interface CEREMA sur un mac aujourd'hui. Je ne pouvais cependant pas associer les outils externes (type exiftool) via le menu `paramétrage` car le panneau de sélection me permettait uniquement de visualiser les fichiers cachés mais pas de les sélectionner (ceux-ci apparaissaient en grisé).

Après quelques recherches, j'ai trouvé [cette solution](https://stackoverflow.com/q/19264922/7060811) sur un forum.

J'ai donc simplement commenté la ligne correspondante dans la fonction d'association (lignes 3370-3374) et cela fonctionne.

Peut-être qu'il y a un petit correctif à proposer pour gérer cela sur mac ?

```python
source=tkinter.filedialog.askopenfilename(initialdir=os.path.dirname(self.exiftool),                                                 
                                          #filetypes=[("exiftool","exiftool*"),(_("Tous"),"*")],
                                          multiple=False,
                                          title = _("Recherche exiftool"))
```

**Comment by Jouin** [comment]
Hello,
My apologies for such a late answer ... The issue had escaped me.
And thanks for your research on MacOs.
I will take this note into account in the next version of the interface.
Best regards.
Denis Jouin
PS: recent innovations of the interface may interest you: taking into account photos for calibration only, tapas with the option Figee after calibration, tool to work with multiple cameras simultaneously, adding Campari to improve the Z points GPS ...
-----------
Bonjour,
Toutes mes excuses pour une réponse si tardive... L'issue m'avait échappée.
Et merci pour vos recherches concernant MacOs. 
Je vais prendre en compte cette remarque dans la prochaine version de l'interface.
Bien cordialement.
Denis Jouin
PS : les nouveautés récentes de l'interface peuvent vous intéresser : prise en compte de photos pour la calibration seulement, tapas avec l'option Figee après calibration, outil pour travailler avec plusieurs appareils photos simultanément, ajout de Campari pour améliorer le Z des points GPS...

**Comment by Jouin** [comment]
Bonjour,

La version 5.30 du 21 février 2019 prend en compte la solution proposée ci-dessus.
Merci de votre contribution
