### ISSUE TITLE
fermeture instantanée de tapioca

### ISSUE THREAD

**Issue by 3dsman** [micmacIGN/InterfaceCEREMA#11]
Je découvre juste l'interface cerema pour micmac et j'ai voulu lancer quelques jeux de donnée de test.
Dès la première étape je rencontre ce problème sur tous mes tests: une fermeture instantanée de tapioca a son lancement.
Il marche sans problème en ligne de commande et les étapes suivantes ont l'air de fonctionner aussi

Dans le commit a8d519bb de la Version 5.31 du 8 mars 2019 vous avez modifié le filtre pour la trace synthèse de tapioca en ajoutant ces deux lignes au début de la méthode filtreTapioca(self,ligne)
        try: self.exe.terminate()
        except Exception as e : print("erreur self.exe.terminate=",str(e))

Ors cette méthode est appelée pour chaque ligne de la sortie pendant l'exécution de tapioca.
son appel des la première ligne ferme instantanément tapioca et fait apparaître une erreur dans l'interface

Si je commente ces deux lignes l'exécution s'effectue sans problème

mon système: laptop sous linux mint 19.3 (Tricia)

**Comment by Jouin** [comment]
Ok, merci de votre remarque : je n'ai plus de système sous Linux à disposition, je ne peux plus effectuer les tests nécessaires. Le fonctionnement de terminate() est différent sous windows et sous linux.
Je viens de retirer les 2 lignes en cause, mea culpa.

**Comment by 3dsman** [comment]
Pas de soucis, c'est a ça que sert l'Open Source 😉
Merci pour votre travail.
