### ISSUE TITLE
Interface can't select exiftool/convert/mashlab on MacOS

### ISSUE THREAD

**Issue by CarlosGrohmann** [micmacIGN/InterfaceCEREMA#3]
Hi, after installing micmac successfully and managed to run one of the tutorial examples via command line, I wanted to try the CEREMA GUI. After getting it to work, I started it and tried to define the path to the executables of micmac/exiftool/convert/mashlab. Setting the path for micmac worked fine, but for the others it didn't worked at all. The dialog opened for file selection wasn't reading the contents of any directory, therefor the "ok" button was greyed out.

After looking a bit the code, I found that the functions `repExiftool`, `repConvert`, `repMeslab` and `repFfmpeg` all were opening the dialogs as `tkinter.filedialog.askopenfilename`. After some searching, I found one answer in StackOverflow (https://stackoverflow.com/questions/19264922/using-askopenfilename-in-python-on-mac) saying that since MacOS doesn't have a "file type" drop menu, you need to remove that from the function call, so in order for it to work fine on macs, there would need to be a checking for system type (like in the `repMicmac` function), and calling `tkinter.filedialog.askopenfilename` with the appropriate  parameters.

Should I make the changes and submit a PR?

**Comment by Jouin** [comment]
Hello,
My apologies for such a late answer ... The issue had escaped me.
And thanks for your research on MacOs.
I will take this note into account in the next version of the interface.
Best regards.
Denis Jouin
PS: recent innovations of the interface may interest you: taking into account photos for calibration only, tapas with the option Figee after calibration, tool to work with multiple cameras simultaneously, adding Campari to improve the Z points GPS ...

Bonjour,
Toutes mes excuses pour une réponse si tardive... L'issue m'avait échappée.
Et merci pour vos recherches concernant MacOs.
Je vais prendre en compte cette remarque dans la prochaine version de l'interface.
Bien cordialement.
Denis Jouin
PS : les nouveautés récentes de l'interface peuvent vous intéresser : prise en compte de photos pour la calibration seulement, tapas avec l'option Figee après calibration, outil pour travailler avec plusieurs appareils photos simultanément, ajout de Campari pour améliorer le Z des points GPS...

**Comment by Jouin** [comment]
Hello, the solution proposed above is in version 5.30 released on February 21, 2019.
Thank you for your contribution
