### ISSUE TITLE
Prompt "new release on internet" either if it's the last release which is running

### ISSUE THREAD

**Issue by XRolland** [micmacIGN/InterfaceCEREMA#4]
As described in title, it occures in launching a project, whenever it's the same last release 5.21

Au chargement d'un projet, un message me signale qu'une nouvelle version de AperoDeDenis est  disponible, même  si je dispose de la dernière version 

AperoDedenis 5.21 Win64, downloaded on GitHub

**Comment by Jouin** [comment]
La version 5.22 du 11 février 2019 supprime cette fonction.
Il n'y a plus de message avertissant qu'une nouvelle version est disponible sur GitHub.
(Je pense que GitHub a modifié certaines caractéristiques de son entête, que je n'ai pas encore intégrées)
