### ISSUE TITLE
InterfaceCEREMA source code

### ISSUE THREAD

**Issue by WF946773243** [micmacIGN/InterfaceCEREMA#8]
I didn't find the source code of InterfaceCEREMA. Isn't it open source?Thanks！

**Comment by kikislater** [comment]
Here are the sources : 
https://github.com/micmacIGN/InterfaceCEREMA/blob/master/InterfaceCEREMA/AperoDeDenis.py

A python script ... Could not be more open !

**Comment by kikislater** [comment]
But you're right ... License file is missing

**Comment by XRolland** [comment]
Fort the license, it was proposed in a ugly PR (sorry, my first one) with some changes in the readme, but never merged.

**Comment by WF946773243** [comment]
Thanks

**Comment by WF946773243** [comment]
I found that if the number of pictures exceeds 250, will it not work?

**Comment by Jouin** [comment]
InterfaceCerema will not work when the number of pictures exceeds about  250 pictures. 
You can use Micmac without InterfaceCerema or you can split your photos into several batches with a few photos in common and then merge the point clouds.

**Comment by Jouin** [comment]
License file is missing

Interface Cerema is under license CECILL-B. I add a license.txt in GitHub.
thanks for the remark
