### ISSUE TITLE
Please stop putting the "Release.msi" file in the repository

### ISSUE THREAD

**Issue by MayeulC** [micmacIGN/InterfaceCEREMA#9]
And more generally, any binary file not necessary for compiling, especially if that one often changes.

It makes the repository annoyingly huge for no good reason. Instead, please consider tagging a commit and using a [release page](https://github.com/micmacIGN/InterfaceCEREMA/releases) to put the file there. There are probably many good resources on how to best use them. Oh, and feel free to copy the release notes there as well.

I am on an ADSL connection, in French countryside. The clone is now 220 MB and counting, this has been going on for a solid 20 minutes. And yes, I could have done a shallow clone, but I'll just wait this one out :)

Edit: 634.19 MiB. One fourth of the whole Linux Kernel repository :)

**Comment by jujudusud** [comment]
Also surprised that  binary files are included with the source instead of been putting apart.
+1

**Comment by Jouin** [comment]
Ok, I'm removing the msi files. I just leave a link to the current msi file.
The msi installer avoids installing python and good libraries, it makes it easier to get started with the application.

**Comment by MayeulC** [comment]
Of course, I didn't mean to imply that it was useless, and there's nothing wrong with providing it as a [release](https://github.com/micmacIGN/InterfaceCEREMA/releases) or so, but git is notoriously bad with large binary files, unless you use a virtual filesystem or git Large File Storage.

Though, truth be told, it *is* useless to me and to anyone else on non-windows platforms :)
